spring:
  application:
    name: agroanalysis

http:
  satveg:
    base-url: "https://api.cnptia.embrapa.br/satveg/v2"
    uri: "/series"
    api-key: ${SATVEG_API_KEY}
  openmeteo:
    base-url: "https://api.open-meteo.com/v1"
    uri: "/forecast"

ai:
  llm:
    url: "https://api.groq.com/openai/v1"
    model: "openai/gpt-oss-20b"
    api-key: ${LLM_API_KEY}